---
- name: Config web VM with docker
  hosts: webservers
  become: true
  tasks:
    - name: docker.io
      apt:
        update_cache: yes
        name: docker.io
        state: present
    - name: install python pip3
      apt:
        name: python3-pip
        state: present
    - name: install docker python module
      pip:
        name: docker
        state: present
    - name: download and launch docker container
      docker_container:
        name: dvwa
        image: cyberxsecurity/dvwa
        state: started
        published_ports: 80:80
        restart_policy: always
    - name: enable docker service
      systemd:
        name: docker
        enabled: yes